apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-relearn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-relearn-api
  template:
    metadata:
      labels:
        app: azure-relearn-api
    spec:
      containers:
      - name: azure-relearn-api
        image: amitjoshipune/azure-relearn-webapi:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT  
            value: "Development"