apiVersion: v1
kind: Service
metadata:
  name: azure-relearn-api-service
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 80          # Publicly exposed port
      targetPort: 8080  # Port your container listens on
      # nodePort: 30081
  selector:
    app: azure-relearn-api